site_name: A Senseable Python Template
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Use Your Project: using-your-project.md
  - Publish Your Code: publish-your-code.md

theme: readthedocs
